UserManagement.Web/Models/Logs/UserLogListViewModel.cs
using System;

namespace UserManagement.Web.Models.Logs;

public class UserLogListViewModel
{
    public List<UserLogListItemViewModel> Items { get; set; } = new();
    public int CurrentPage { get; set; }
    public int TotalPages { get; set; }
    public int PageSize { get; set; }
}

public class UserLogListItemViewModel
{
    public long Id { get; set; }
    public required long UserId { get; set; }
    public required string Forename { get; set; }
    public required string Surname { get; set; }
    public required string Action { get; set; }
    public DateTime ActionDate { get; set; }
    public string? AdditionalInfo { get; set; }
}

UserManagement.Web/Models/Users/UserAddViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace UserManagement.Web.Models.Users;

public class UserAddViewModel
{
    [Required(ErrorMessage = "Forename is required.")]
    public required string Forename { get; set; }

    [Required(ErrorMessage = "Surname is required.")]
    public required string Surname { get; set; }

    [Required(ErrorMessage = "Email is required.")]
    [EmailAddress(ErrorMessage = "Invalid email address.")]
    public required string Email { get; set; }

    public bool IsActive { get; set; }

    [Range(typeof(DateTime), "1900-01-01", "2099-12-31", ErrorMessage = "Date of birth must be between 01/01/1900 and 31/12/2099.")]
    public required DateTime DateOfBirth { get; set; }
}

UserManagement.Web/Models/Users/UserDeleteViewModel.cs
namespace UserManagement.Web.Models.Users
{
    public class UserDeleteViewModel
    {
        public long Id { get; set; }
        public string Forename { get; set; } = default!;
        public string Surname { get; set; } = default!;
    }
}

UserManagement.Web/Models/Users/UserEditViewModel.cs
namespace UserManagement.Web.Models.Users
{
    public class UserEditViewModel : UserModel { }
}

UserManagement.Web/Models/Users/UserListViewModel.cs
namespace UserManagement.Web.Models.Users;

public class UserListViewModel
{
    public List<UserListItemViewModel> Items { get; set; } = new();
}

public class UserListItemViewModel : UserModel { }

UserManagement.Web/Models/Users/UserModel.cs
using System;

namespace UserManagement.Web.Models.Users;
public class UserModel
{
    public long Id { get; set; }
    public string Forename { get; set; } = default!;
    public string Surname { get; set; } = default!;
    public string Email { get; set; } = default!;
    public bool IsActive { get; set; }
    public DateTime DateOfBirth { get; set; }
}

UserManagement.Web/Models/Users/UserViewModel.cs
using UserManagement.Models;

namespace UserManagement.Web.Models.Users
{
    public class UserViewModel : UserModel {
        public List<UserActionLog> UserActionLogs { get; set; } = [];
     }
}

UserManagement.Web/Controllers/HomeController.cs
namespace UserManagement.WebMS.Controllers;

public class HomeController : Controller
{
    [HttpGet]
    public ViewResult Index() => View();
}

UserManagement.Web/Controllers/LogsController.cs
using System;
using System.Linq;
using UserManagement.Services.Domain.Interfaces;
using UserManagement.Web.Models.Logs;

namespace UserManagement.Web.Controllers;

[Route("logs")]
public class LogsController : Controller
{
    private readonly ILogsService _logsService;
    public LogsController(ILogsService logsService) => _logsService = logsService;

    [HttpGet]
    public ViewResult List(int page = 1)
    {
        const int pageSize = 10;
        var logs = _logsService.GetAllLogs();
        var items = logs.Skip((page - 1) * pageSize)
        .Take(pageSize).Select(log => new UserLogListItemViewModel
        {
            Id = log.Id,
            Forename = log.Forename,
            Surname = log.Surname,
            UserId = log.UserId,
            Action = log.Action,
            ActionDate = log.ActionDate,
            AdditionalInfo = log.AdditionalInfo
        }).ToList();

        var totalLogs = logs.Count();
        var totalPages = (int)Math.Ceiling((double)totalLogs / pageSize);

        var model = new UserLogListViewModel
        {
            Items = items,
            CurrentPage = page,
            PageSize = pageSize,
            TotalPages = totalPages
        };

        return View(model);
    }
}

UserManagement.Web/Controllers/UsersController.cs
using System.Linq;
using UserManagement.Models;
using UserManagement.Services.Domain.Interfaces;
using UserManagement.Web.Models.Users;

namespace UserManagement.WebMS.Controllers;

[Route("users")]
public class UsersController : Controller
{
    private readonly IUserService _userService;
    private readonly ILogsService _logsService;
    public UsersController(IUserService userService, ILogsService logsService)
    {
        _userService = userService;
        _logsService = logsService;
    }
    [HttpGet]
    public ViewResult List(bool? activeStatus = null)
    {
        var users = activeStatus.HasValue ? _userService.FilterByActive(activeStatus.Value) : _userService.GetAll();
        var items = users.Select(p => new UserListItemViewModel
        {
            Id = p.Id,
            Forename = p.Forename,
            Surname = p.Surname,
            Email = p.Email,
            IsActive = p.IsActive,
            DateOfBirth = p.DateOfBirth
        });

        var model = new UserListViewModel
        {
            Items = items.ToList()
        };

        return View(model);
    }

    [HttpGet("add-user")]
    public ViewResult AddUser()
    {
        return View();
    }

    [HttpPost("add")]
    public ActionResult Add(UserAddViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View("AddUser", model);
        }

        var user = new User
        {
            Forename = char.ToUpper(model.Forename[0]) + model.Forename.Substring(1),
            Surname = char.ToUpper(model.Surname[0]) + model.Surname.Substring(1),
            Email = model.Email,
            IsActive = model.IsActive,
            DateOfBirth = model.DateOfBirth
        };

        _userService.Add(user);

        return RedirectToAction("List");
    }

    [HttpGet("view")]
    public ViewResult View([FromQuery] long id)
    {
        var user = _userService.GetById(id);

        var userLogs = _logsService.GetAllLogs().Where(log => log.UserId == user.Id);

        var viewModel = new UserViewModel
        {
            Forename = user.Forename,
            Surname = user.Surname,
            Email = user.Email,
            IsActive = user.IsActive,
            DateOfBirth = user.DateOfBirth,
            UserActionLogs = userLogs.Select(log => new UserActionLog
            {
                Id = log.Id,
                UserId = log.UserId,
                Forename = log.Forename,
                Surname = log.Surname,
                Action = log.Action,
                ActionDate = log.ActionDate,
                AdditionalInfo = log.AdditionalInfo
            }).ToList()
        };

        return View(viewModel);
    }

    [HttpGet("edit-user")]
    public ViewResult EditUser([FromQuery] long id)
    {
        var user = _userService.GetById(id);

        var editModel = new UserEditViewModel
        {
            Forename = user.Forename,
            Surname = user.Surname,
            Email = user.Email,
            IsActive = user.IsActive,
            DateOfBirth = user.DateOfBirth
        };

        return View(editModel);
    }

    [HttpPost("edit")]
    public ActionResult Edit(UserEditViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View("EditUser", model);
        }

        var user = _userService.GetById(model.Id);
        if (user == null)
        {
            return NotFound();
        }

        user.Forename = char.ToUpper(model.Forename[0]) + model.Forename.Substring(1);
        user.Surname = char.ToUpper(model.Surname[0]) + model.Surname.Substring(1);
        user.Email = model.Email;
        user.IsActive = model.IsActive;
        user.DateOfBirth = model.DateOfBirth;

        _userService.Edit(user);

        return RedirectToAction("List");
    }

    [HttpGet("delete-confirm")]
    public ViewResult DeleteConfirm([FromQuery] long id)
    {
        var user = _userService.GetById(id);

        var deleteModel = new UserDeleteViewModel
        {
            Forename = user.Forename,
            Surname = user.Surname,
        };

        return View(deleteModel);
    }

    [HttpPost("delete")]
    public ActionResult Delete(long id)
    {
        var user = _userService.GetById(id);
        if (user == null)
        {
            return NotFound();
        }

        _userService.Delete(user);

        return RedirectToAction("List");
    }
}

UserManagement.Web/Views/Home/Index.cshtml
@using Westwind.AspNetCore.Markdown

@{
    ViewBag.Title = "Home";
}

@Markdown.ParseHtmlStringFromFile("../../README.md")

<p>
    <a asp-controller="Users" asp-action="List" class="btn btn-primary">To User List</a>
</p>

UserManagement.Web/Views/Logs/List.cshtml
@model UserManagement.Web.Models.Logs.UserLogListViewModel

<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>User ID</th>
                <th>Name</th>
                <th>Action</th>
                <th>Action Date</th>
                <th>Additional Info</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var log in Model.Items)
            {
                <tr>
                    <td>@log.UserId</td>
                    <td>@log.Forename @log.Surname</td>
                    <td>@log.Action</td>
                    <td>@log.ActionDate</td>
                    <td>@log.AdditionalInfo</td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="pagination d-flex gap-4">
    @if (Model.Items.Count() > 0)
    {
        <p>Page: </p>
    }
    @if (Model.CurrentPage > 1)
    {
        <a href="?page=@(Model.CurrentPage - 1)">Previous</a>
    }
    @for (var i = 1; i <= Model.TotalPages; i++)
    {
        if (i == Model.CurrentPage)
        {
            <span>@i</span>
        }
        else
        {
            <a href="?page=@i">@i</a>
        }
    }
    @if (Model.CurrentPage < Model.TotalPages)
    {
        <a href="?page=@(Model.CurrentPage + 1)">Next</a>
    }
</div>

UserManagement.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - helloworld</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/helloworld.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">User Management</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Users" asp-action="List">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Logs" asp-action="List">Logs</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UserManagement.Web/Views/Users/Add.cshtml
@model UserManagement.Web.Models.Users.UserAddViewModel

<h2 class="mb-4">Add User</h2>

<form asp-action="Add" asp-controller="Users" method="post">
    <div class="form-group row-cols-2">
        <label for="Forename" class="col-sm-2 col-form-label">Forename:</label>
        <input id="Forename" name="Forename" type="text" asp-for="Forename" />
        <span asp-validation-for="Forename" class="ml-4 text-danger"></span>
    </div>
    <div class="form-group row-cols-2">
        <label for="Surname" class="col-sm-2 col-form-label">Surname:</label>
        <input id="Surname" name="Surname" type="text" asp-for="Surname" />
        <span asp-validation-for="Surname" class="ml-4 text-danger"></span>
    </div>
    <div class="form-group row-cols-2">
        <label for="Email" class="col-sm-2 col-form-label">Email:</label>
        <input id="Email" name="Email" type="email" asp-for="Email" />
        <span asp-validation-for="Email" class="ml-4 text-danger"></span>
    </div>
    <div class="form-group">
        <label for="IsActive" class="col-sm-2 col-form-label">Active:</label>
        <input id="IsActive" name="IsActive" type="checkbox" asp-for="IsActive" />
    </div>
    <div class="form-group row-cols-8">
        <label for="DateOfBirth" class="col-sm-2 col-form-label">Date of Birth:</label>
        <input id="DateOfBirth" name="DateOfBirth" type="date" asp-for="DateOfBirth" />
        <span asp-validation-for="DateOfBirth" class="ml-4 text-danger"></span>
    </div>
    <div class="form-group row mt-4">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Add User</button>
        </div>
    </div>
</form>

UserManagement.Web/Views/Users/AddUser.cshtml
@model UserManagement.Web.Models.Users.UserAddViewModel

<h2 class="mb-4">Add User</h2>

<form asp-action="Add" asp-controller="Users" method="post">
    <div class="form-group row-cols-2">
        <label for="Forename" class="col-sm-2 col-form-label">Forename:</label>
        <input id="Forename" name="Forename" type="text" asp-for="Forename" />
        <span asp-validation-for="Forename" class="ml-4 text-danger"></span>
    </div>
    <div class="form-group row-cols-2">
        <label for="Surname" class="col-sm-2 col-form-label">Surname:</label>
        <input id="Surname" name="Surname" type="text" asp-for="Surname" />
        <span asp-validation-for="Surname" class="ml-4 text-danger"></span>
    </div>
    <div class="form-group row-cols-2">
        <label for="Email" class="col-sm-2 col-form-label">Email:</label>
        <input id="Email" name="Email" type="email" asp-for="Email" />
        <span asp-validation-for="Email" class="ml-4 text-danger"></span>
    </div>
    <div class="form-group">
        <label for="IsActive" class="col-sm-2 col-form-label">Active:</label>
        <input id="IsActive" name="IsActive" type="checkbox" asp-for="IsActive" />
    </div>
    <div class="form-group row-cols-8">
        <label for="DateOfBirth" class="col-sm-2 col-form-label">Date of Birth:</label>
        <input id="DateOfBirth" name="DateOfBirth" type="date" asp-for="DateOfBirth" />
        <span asp-validation-for="DateOfBirth" class="ml-4 text-danger"></span>
    </div>
    <div class="form-group row mt-4">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Add User</button>
        </div>
    </div>
</form>

UserManagement.Web/Views/Users/DeleteConfirm.cshtml
@model UserManagement.Web.Models.Users.UserDeleteViewModel

<h2 class="mb-4">Delete User @Model.Forename @Model.Surname?</h2>

<form asp-action="Delete" asp-controller="users" method="post">
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        <input type="submit" value="Delete" class="btn btn-danger col-sm-2" />
        <a asp-action="Index" class="btn btn-secondary col-sm-2">Cancel</a>
    </div>
</form>

UserManagement.Web/Views/Users/Edit.cshtml
@model UserManagement.Web.Models.Users.UserEditViewModel

<h2 class="mb-4">Edit User</h2>

<form asp-action="Edit" asp-controller="Users" method="post">
    @Html.HiddenFor(model => model.Id)
    <div class="form-group row-cols-2">
        <label for="Forename" class="col-sm-2 col-form-label">Forename:</label>
        <input id="Forename" name="Forename" type="text" asp-for="Forename" value="@Model.Forename" />
        <span asp-validation-for="Forename" class="ml-4 text-danger"></span>
    </div>
    <div class="form-group row-cols-2">
        <label for="Surname" class="col-sm-2 col-form-label">Surname:</label>
        <input id="Surname" name="Surname" type="text" asp-for="Surname" value="@Model.Surname" />
        <span asp-validation-for="Surname" class="ml-4 text-danger"></span>
    </div>
    <div class="form-group row-cols-2">
        <label for="Email" class="col-sm-2 col-form-label">Email:</label>
        <input id="Email" name="Email" type="email" asp-for="Email" value="@Model.Email" />
        <span asp-validation-for="Email" class="ml-4 text-danger"></span>
    </div>
    <div class="form-group">
        <label for="IsActive" class="col-sm-2 col-form-label">Active:</label>
        <input id="IsActive" name="IsActive" type="checkbox" asp-for="IsActive" checked="@Model.IsActive" />
    </div>
    <div class="form-group row-cols-8">
        <label for="DateOfBirth" class="col-sm-2 col-form-label">Date of Birth:</label>
        <input id="DateOfBirth" name="DateOfBirth" type="date" asp-for="DateOfBirth"
            value="@Model.DateOfBirth.ToString("yyyy-MM-dd")" />
        <span asp-validation-for="DateOfBirth" class="ml-4 text-danger"></span>
    </div>
    <div class="form-group row mt-4">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Update</button>
        </div>
    </div>
</form>

UserManagement.Web/Views/Users/EditUser.cshtml
@model UserManagement.Web.Models.Users.UserEditViewModel

<h2 class="mb-4">Edit User</h2>

<form asp-action="Edit" asp-controller="Users" method="post">
    @Html.HiddenFor(model => model.Id)
    <div class="form-group row-cols-2">
        <label for="Forename" class="col-sm-2 col-form-label">Forename:</label>
        <input id="Forename" name="Forename" type="text" asp-for="Forename" value="@Model.Forename" />
        <span asp-validation-for="Forename" class="ml-4 text-danger"></span>
    </div>
    <div class="form-group row-cols-2">
        <label for="Surname" class="col-sm-2 col-form-label">Surname:</label>
        <input id="Surname" name="Surname" type="text" asp-for="Surname" value="@Model.Surname" />
        <span asp-validation-for="Surname" class="ml-4 text-danger"></span>
    </div>
    <div class="form-group row-cols-2">
        <label for="Email" class="col-sm-2 col-form-label">Email:</label>
        <input id="Email" name="Email" type="email" asp-for="Email" value="@Model.Email" />
        <span asp-validation-for="Email" class="ml-4 text-danger"></span>
    </div>
    <div class="form-group">
        <label for="IsActive" class="col-sm-2 col-form-label">Active:</label>
        <input id="IsActive" name="IsActive" type="checkbox" asp-for="IsActive" checked="@Model.IsActive" />
    </div>
    <div class="form-group row-cols-8">
        <label for="DateOfBirth" class="col-sm-2 col-form-label">Date of Birth:</label>
        <input id="DateOfBirth" name="DateOfBirth" type="date" asp-for="DateOfBirth"
            value="@Model.DateOfBirth.ToString("yyyy-MM-dd")" />
        <span asp-validation-for="DateOfBirth" class="ml-4 text-danger"></span>
    </div>
    <div class="form-group row mt-4">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Update</button>
        </div>
    </div>
</form>

UserManagement.Web/Views/Users/List.cshtml
@model UserManagement.Web.Models.Users.UserListViewModel

<h2>User List</h2>

<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Forename</th>
                <th>Surname</th>
                <th>Email</th>
                <th>Account Active</th>
                <th>Date Of Birth</th>
                <th style="width: 1px;"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Items)
            {
                <tr>
                    <td>
                        @item.Id
                    </td>
                    <td>
                        @item.Forename
                    </td>
                    <td>
                        @item.Surname
                    </td>
                    <td>
                        @item.Email
                    </td>
                    <td>
                        @(item.IsActive ? "Yes" : "No")
                    </td>
                    <td>
                        @item.DateOfBirth.ToString("dd/MM/yyyy")
                    </td>
                    <td>
                        <div class="dropdown">
                            <button type="button" class="btn btn-default dropdown-toggle" data-bs-toggle="dropdown"
                                aria-expanded="false" id="btnToggleActions">
                                Actions
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="btnToggleActions">
                                <li><a class="dropdown-item" asp-controller="Users" asp-action="View"
                                        asp-route-id="@item.Id">View</a></li>
                                <li><a class="dropdown-item" asp-controller="Users" asp-action="EditUser"
                                        asp-route-id="@item.Id">Edit</a></li>
                                <li><a class="dropdown-item" asp-controller="Users" asp-action="DeleteConfirm"
                                        asp-route-id="@item.Id">Delete</a></li>
                            </ul>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div>
    <div class="btn-group" role="group">
        <a asp-controller="Users" asp-action="List" class="btn btn-default">Show All</a>
        <a class="btn btn-default" asp-controller="Users" asp-action="List" asp-route-activeStatus="true">Active
            Only</a>
        <a class="btn btn-default" asp-controller="Users" asp-action="List" asp-route-activeStatus="false">Non
            Active</a>
    </div>

    <a asp-controller="users" asp-action="AddUser" class="btn btn-primary float-end">
        Add User
    </a>
</div>

UserManagement.Web/Views/Users/View.cshtml
@model UserManagement.Web.Models.Users.UserViewModel

<div class="container">
    <h1 class="mb-4">@Model.Forename @Model.Surname</h1>

    <div class="row-cols-2">
        <div class="pb-2">
            <h4 class="fw-bold">Email:</h4>
            <p>@Model.Email</p>
        </div>
        <div class="pb-2">
            <h4 class="fw-bold">Active:</h4>
            <p>@(Model.IsActive ? "Yes" : "No")</p>
        </div>
        <div class="pb-2">
            <h4 class="fw-bold">Date of Birth:</h4>
            <p>@Model.DateOfBirth.ToString("dd/MM/yyyy")</p>
        </div>

        <table class="table table-striped my-4">
        <thead>
            <tr>
                <th>Action</th>
                <th>Action Date</th>
                <th>Additional Info</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var log in Model.UserActionLogs)
            {
                <tr>
                    <td>@log.Action</td>
                    <td>@log.ActionDate.ToString("dd/MM/yyyy")</td>
                    <td>@log.AdditionalInfo</td>
                </tr>
            }
        </tbody>
    </table>

        <a class="btn btn-primary" asp-controller="users" asp-action="Index">Return to User List</a>
    </div>
</div>